import type { Cue } from './cue';
import { formatAssTimestamp, parseAssTimestamp } from './cue';

/**
 * ASS/SSA support is deliberately shallow: we read the `[Events]` Dialogue
 * lines, strip `{...}` override tags, and turn `\N`/`\n` into plain
 * newlines — so round-tripping recovers the cue *text* and timing, but not
 * karaoke tags, per-run styling, or positioning. `style` on the Cue carries
 * only the named style (e.g. "Default"), not its formatting. See index.ts
 * for how this is priced (retention < 1 leaving ASS).
 */

/** Split a comma-separated line into `maxFields` parts, keeping the last field intact. */
function splitAssFields(line: string, maxFields: number): string[] {
  const parts: string[] = [];
  let rest = line;
  for (let i = 0; i < maxFields - 1; i++) {
    const idx = rest.indexOf(',');
    if (idx === -1) {
      parts.push(rest);
      rest = '';
      break;
    }
    parts.push(rest.slice(0, idx));
    rest = rest.slice(idx + 1);
  }
  parts.push(rest);
  return parts;
}

/** Strip `{...}` override blocks and normalize ASS line-break escapes. */
function cleanAssText(raw: string): string {
  return raw
    .replace(/\{[^}]*\}/g, '')
    .replace(/\\N/g, '\n')
    .replace(/\\n/g, '\n')
    .replace(/\\h/g, ' ')
    .trim();
}

/** Parse an ASS/SSA document into cues (plain text only — see module doc). */
export function parseAss(source: string): Cue[] {
  const lines = source.replace(/\r\n/g, '\n').split('\n');
  const cues: Cue[] = [];
  let inEvents = false;
  let textFieldIndex = 9; // default V4+ Dialogue field order

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (/^\[.*\]$/.test(line)) {
      inEvents = /^\[Events\]$/i.test(line);
      continue;
    }
    if (!inEvents) continue;

    if (/^Format:/i.test(line)) {
      const fields = line
        .slice(line.indexOf(':') + 1)
        .split(',')
        .map((f) => f.trim().toLowerCase());
      const idx = fields.indexOf('text');
      if (idx >= 0) textFieldIndex = idx;
      continue;
    }

    if (!/^Dialogue:/i.test(line)) continue;

    const body = line.slice(line.indexOf(':') + 1).trim();
    const parts = splitAssFields(body, textFieldIndex + 1);
    const start = parts[1] ?? '';
    const end = parts[2] ?? '';
    const style = parts[3]?.trim();
    const text = cleanAssText(parts[textFieldIndex] ?? '');

    cues.push({
      start: parseAssTimestamp(start),
      end: parseAssTimestamp(end),
      text,
      style: style && style.length > 0 ? style : undefined,
    });
  }

  return cues;
}

/** Serialize cues to a minimally valid V4+ ASS document. */
export function serializeAss(cues: readonly Cue[]): string {
  const header = [
    '[Script Info]',
    '; Script generated by File Warper',
    'ScriptType: v4.00+',
    'WrapStyle: 0',
    'ScaledBorderAndShadow: yes',
    'YCbCr Matrix: None',
    'PlayResX: 384',
    'PlayResY: 288',
    '',
    '[V4+ Styles]',
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
    'Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1',
    '',
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
  ].join('\n');

  const events = cues
    .map((cue) => {
      const style = cue.style && cue.style.length > 0 ? cue.style : 'Default';
      const text = cue.text.replace(/\n/g, '\\N');
      return `Dialogue: 0,${formatAssTimestamp(cue.start)},${formatAssTimestamp(cue.end)},${style},,0,0,0,,${text}`;
    })
    .join('\n');

  return events.length > 0 ? `${header}\n${events}\n` : `${header}\n`;
}
